# LAN Machines Config
machines:
    # ORDER MATTERS FOR THESE VALUES
    machineHostnames:
    - 'localhost'
    - 'media.server'
    machineMacAddrs:
    - '00:00:00:00:00:00'
    - '00:00:00:00:00:01'

# Minecraft Server Config
mcServer:
  serverHostName: 'localhost'
  tlsProtection: false
  tlsCertDir: '/usr/local/ssl'
  # ORDER MATTERS FOR THESE VALUES
  mcServerAddr: 
  - 'play1.addr.mc'
  - 'play2.addr.mc'
  mcServerAliases:
    # api/mc-server calls must contain this in a parameter to specify which server is being called for
  - 'survival-world'
  - 'creative-world'
  mcServerContainerName: 
  - 'mc-container-1'
  - 'mc-container-2'

# VPS Config
vps:
    vpsHostname: 'hostnameOrIpAddress.local'
    dropletID: 123456789
    # In Seconds
    startDelay: 10
    timeOut: 600
